### ISSUE TITLE
License and packaging

### ISSUE THREAD

**Issue by gisjedi** [boundlessgeo/django-geoaxis#2]
We have a number of Apache v2 licensed open-source projects (http://github.com/ngageoint/scale being one) that we'd like to use this package in, but the GPL v3 license is problematic for that. Would it be possible to re-license this under Apache or another license that is less viral in nature?

It would also be nice to see this published in PyPI for easy inclusion via project `requirements.txt` files. I'd be more than happy to assist in this, if that would facilitate the work. 

Thanks for open-sourcing this backend!

**Comment by tingold** [comment]
We've changed the license to MIT -- which is Apache compatible. 

Enjoy

**Comment by gisjedi** [comment]
Thanks @tingold. Appreciate the support.
